### PR TITLE
Use pixel scalings instead of points

### PR DESCRIPTION
**Pull request by mfurseman**
This should make converted screens use the new pixel font sizes, which gives better behaviour on different DPI monitors.

### CODE REVIEW

**Comment by nickbattam** [comment]
@mfurseman  The unit tests (OpiFontTest.java) should be updated to check this value

**Comment by mfurseman** [comment]
The actual check is currently [commented out](https://github.com/dls-controls/cs-studio/blob/ede54cdfd3adc1fdc3b04a2bb48b5d6272737eaf/applications/opibuilder/opibuilder-plugins/org.csstudio.opibuilder.converter.test/src/org/csstudio/opibuilder/converter/writer/XMLFileHandler.java#L160). Do you think we should reinstate this check with our size conversion factor included?

**Comment by nickbattam** [comment]
Yes. We should add a check that we get the correct behaviour with both Pixel and Point font scaling too.

**Comment by mfurseman** [comment]
The converter can no longer attempt to convert to points, the conversion to pixels is hard coded into OpiFont class. We shouldn't need to use points when converting from EDM!

I've updated the converter tests so they are checking the font size as well.

**Pull request merged**
