### PR TITLE
Move xmlunit from Package to Bundle requirement

### PR DESCRIPTION
**Pull request by nickbattam**
@willrogers

### CODE REVIEW

**Comment by willrogers** [comment]
Does it work...?

**Comment by nickbattam** [comment]
Yes. Just checking everything else still does too - hold of merging for now

**Comment by nickbattam** [comment]
Full builds of the product, both on and offline succeed. 
The tests in org.csstudio.utility.treemodel.test pass.

I've raised an issue ticket on the cs-studio repo.

**Comment by willrogers** [comment]
Should I merge?

**Pull request merged**
