### PR TITLE
o.c.trends.databrowser2: archive search view double-click

### PR DESCRIPTION
**Pull request by willrogers**
This opens the data browser editor with a double click in the search
view, instead of (or as well as) being able to use the right-click
menu.

@nickbattam is this the right branch to merge into?

### CODE REVIEW

**Comment by nickbattam** [comment]
@willrogers I don't think so, this should merge into integration-4.3 as you don't intend it to be part of the 4.2 release.

**Comment by willrogers** [comment]
And that exists ... ?

**Comment by nickbattam** [comment]
It does now

**Comment by willrogers** [comment]
This has been accepted into `master`, plus a bug-fix by Eric on top of it.  Probably easier just to wait.

**Pull request closed without merging**
